services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./config:/var/www/config
      - ./:/var/www
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: drawmance
      MYSQL_USER: drawuser
      MYSQL_PASSWORD: drawpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: drawuser
      PMA_PASSWORD: drawpass
    depends_on:
      - db

volumes:
  db_data:
